services:
  - type: web
    name: analyzeap
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        generateValue: true
      - key: APP_PASSWORD
        sync: false
      - key: R2_ENDPOINT_URL
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_PRODUCT_MASTER_KEY
        value: product_master.csv
      - key: GA4_CREDENTIALS_JSON
        sync: false
      - key: GA4_PROPERTY_RADY
        sync: false
      - key: GA4_PROPERTY_CHERIMI
        sync: false
      - key: GA4_PROPERTY_MICHELLMACARON
        sync: false
      - key: GA4_PROPERTY_SOLNI
        sync: false
